airport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
    
]

myapp/urls.py
from django.urls import path
from . import views
from .views import progress_view
from django.urls import include

urlpatterns = [
    path('caap_ap',views.index),
    path('view/<int:id>',views.viewProject),
    path('show/<int:id>',views.showView),
    path('dashboard',views.dashView),
    path('',views.login_view),
    # path('search',views.searchView),   
    path('logout',views.logout_view),    
    path('info/', views.infoView),
    path('addnew',views.addnew),
    path('complete-projects',views.complete_projects),
    path('ongoing-projects',views.ongoing_projects),
    path('procurement-projects',views.procurement_projects),
    path('edit/<int:id>', views.edit),  
    path('delete/<int:id>', views.destroy),  
    path('update/<int:id>', views.update),  

    path('progress/', views.progress_view),

    
]

myapp/models.py
from django.db import models
from django.forms import TextInput, Textarea

class UserModel(models.Model):
    email = models.EmailField(max_length=254)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

class Employee(models.Model):  
    CATEGORY_CHOICES = [
        ('Complete', 'Complete'),
        ('On-Going', 'On-Going'),
        ('Under Procurement', 'Under Procurement'),
    ]

    SLIPPAGE_CHOICES = [
        ('ANS','ANS',),
        ('Negative','Negative'),
        ('Positive','Positive'),
        ('Pending','Pending'),
        ('Terminated','Terminated'),
        ('Blanks','Blanks')
    ]
    loc = models.CharField(max_length=1000)  
    title = models.CharField(max_length=1000, null=True, blank=True)
    desc = models.TextField(max_length=1000, null=True)  
    fund = models.TextField(max_length=1000, null=True)
    cont = models.TextField(max_length=1000, null=True)
    proj_profile = models.TextField()
    proj_stat = models.CharField(max_length=1000, choices=CATEGORY_CHOICES, null=True)
    proj_comment = models.TextField(max_length=1000)
    slip = models.CharField(max_length=1000, choices=SLIPPAGE_CHOICES, null=True)
    budg = models.IntegerField(max_length=1000, null=True) 
    agency = models.CharField(max_length=1000, null=True) 
    area = models.CharField(max_length=1000, null=True) 
    reg = models.CharField(max_length=1000, null=True) 
    cert = models.CharField(max_length=1000, null=True) 
    reco = models.CharField(max_length=1000, null=True)
    progress = models.IntegerField(null=True, default=0) 

    class Meta:  
        db_table = "employee"

myapp/forms.py
from django import forms  
from myapp.models import Employee  
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewEmployeeForm(forms.ModelForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = Employee
        # specify fields to be used
    #     fields = ['loc', 'fund', 'desc', 'cont', 'proj_profile', 'proj_stat'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
    #     widgets = { 'loc': forms.TextInput(attrs={ 'class': 'form-control' }), 
    #                'desc': forms.Textarea(attrs={'rows':1, 'cols':44}),
    #                'fund': forms.Textarea(attrs={'rows':1, 'cols':44}),
    #                'cont': forms.Textarea(attrs={'rows':1, 'cols':44}),
    #                'proj_profile': forms.Textarea(attrs={'rows':1, 'cols':44}),
    #                'proj_comment': forms.Textarea(attrs={'rows':1, 'cols':44}),
    #                'agency': forms.Textarea(attrs={'rows':1, 'cols':44}),
    #                'cert': forms.Textarea(attrs={'rows':1, 'cols':44}),
                   
    #             #    'proj_stat': forms.Textarea(attrs={'rows':4, 'cols':15}),
    #         # 'desc': forms.TextInput(attrs={ 'class': 'form-control' }),
    #         # 'fund': forms.TextInput(attrs={ 'class': 'form-control' }),
            
    #   }
        fields = '__all__'

myapp/views.py
# views.py
from django.shortcuts import render, redirect
from myapp.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect,
                              redirect)
from .models import *
from .forms import *
from django.db.models import Q

def login_view(request):
    employees = Employee.objects.all()[:300] 
    count_all = Employee.objects.all().count()
    count_complete = Employee.objects.filter(proj_stat="Complete").count()
    count_ongoing = Employee.objects.filter(proj_stat="On-Going").count()
    count_procurement = Employee.objects.filter(proj_stat="Under Procurement").count()
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            error_message = 'Invalid username or password'
    else:
        error_message = ''
    return render(request, 'dashboard.html', {'error_message': error_message, 'employees':employees, 'count_all':count_all, 'count_complete':count_complete, 'count_ongoing':count_ongoing, 'count_procurement':count_procurement})



@login_required

def logout_view(request):
    logout(request)     
    return redirect('/')



def addnew(request):
    context = {}
 
    # add the dictionary during initialization
    form = NewEmployeeForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")
    context['form']= form
    return render(request, "add_record.html", context)


def index(request):
    if 'q' in request.GET:
        q = request.GET['q']
        # data = Data.objects.filter(last_name__icontains=q)
        multiple_q = Q(Q(desc__icontains=q) | Q(loc__icontains=q) | Q(proj_stat__icontains=q))
        employees = Employee.objects.filter(multiple_q)
    else:
        employees = Employee.objects.all()
    context = {
        'employees': employees
    }
    return render(request, 'project_table.html', context)

def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    form = NewEmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/caap_ap")  
    return render(request,'edit.html', {'employee':employee})  



def show_project(request, id): 
    context ={}

    context["project"] = Employee.objects.get(id = id)
          
    return render(request, "show_project.html", context)

def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = NewEmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/caap_ap")  
    return render(request, 'edit.html', {'employee': employee})  


def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/") 


def infoView(request):
    return render(request,'info.html')

def viewProject(request,id):

    view_proj = Employee.objects.get(id = id)

    
        # green
    if view_proj.progress >= 90 and view_proj.progress <= 100:
        progress_color = "#5FD068"
        # blue
    if  view_proj.progress >= 75 and view_proj.progress <= 89:        
        progress_color = "#62CDFF"
        # yello
    if  view_proj.progress >= 30 and view_proj.progress <= 74:
        progress_color = "#FFE15D"
        # red
    if  view_proj.progress >= 0 and view_proj.progress <= 29:
        progress_color = "#FD8A8A"
    
    return render(request,'view.html', {'progress_color': progress_color, 'view' : view_proj })

def showView(request,id):
    context = {}
    context["proj_detail"] = Employee.objects.get(id=id)
    return render(request,'show.html')


def dashView(request):
    employees = Employee.objects.all()[:300] 
    count_all = Employee.objects.all().count()
    count_complete = Employee.objects.filter(proj_stat="Complete").count()
    count_ongoing = Employee.objects.filter(proj_stat="On-Going").count()
    count_procurement = Employee.objects.filter(proj_stat="Under Procurement").count()
    return render(request,"dashboard.html",{'employees':employees, 'count_all':count_all, 'count_complete':count_complete, 'count_ongoing':count_ongoing, 'count_procurement':count_procurement})

def complete_projects(request):
    complete = Employee.objects.filter(proj_stat='Complete').all()

    return render(request,'myapp/status/complete_projects.html', {'complete': complete})

def ongoing_projects(request):
    ongoing = Employee.objects.filter(proj_stat='On-Going').all()

    return render(request,'myapp/status/ongoing_projects.html', {'ongoing': ongoing})


def procurement_projects(request):
    procurement = Employee.objects.filter(proj_stat='Under Procurement').all()

    return render(request,'myapp/status/procurement_projects.html', {'procurement': procurement})

def progress_view(request):
    # Calculate the progress as a percentage of the target number of signups
    total_capacity = 100  # Replace with your own target number
    users = 31
    comp_projects = Employee.objects.filter(proj_stat='Complete').count()
    ongoing_projects = Employee.objects.filter(proj_stat='On-Going').count()
    proc_projects = Employee.objects.filter(proj_stat='Under Procurement').count()
    progress_cp = comp_projects / total_capacity * 100 
    # * 100 is a conversion of int to float
    progress_og = ongoing_projects / total_capacity * 100
    progress_proc = proc_projects / total_capacity * 100
    high = 'green'
    medium = 'orange'
    low = 'red'
    if progress_cp < 30:
        progress_color = low
    elif progress_cp < 80:
        progress_color = medium

    else:
        progress_color = high

    # Render a template that displays the progress bar
    context = {
        'progress_color': progress_color,
        'progress_cp':progress_cp,
        'progress_og':progress_og,
        'progress_proc':progress_proc,
    }

    return render(request, 'sample.html', context)

myapp/templates/add_record.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">

  <link rel="stylesheet" href="{% static 'js/summernote/summernote-bs4.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/addnew.css' %}">
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
</head>

<body>

  <form method="POST" class="addform" action="/addnew">
    <h2>Create Project Details</h2>
    {% csrf_token %}
    <fieldset class="fldset">
      <label class="lbl">Location:</label>
      <div class="inp">{{ form.loc }}</div>
      <label class="lbl">Description:</label>
      <div class="inp">{{ form.desc }}</div>
      <label class="lbl">Funding Particulars:</label>
      <div class="inp">{{ form.fund }}</div>
      <label class="lbl">Contract Description:</label>
      <div class="inp">{{ form.cont }}</div>
      <label class="lbl">Project Profile:</label>
      <div class="inp">{{ form.proj_stat }}</div>
      <label class="lbl">Slippage:</label>
      <div class="inp">{{ form.slip }}</div>
      <label class="lbl">Agency:</label>
      <div class="inp">{{ form.agency }}</div>
      <label class="lbl">Area:</label>
      <div class="inp">{{ form.area }}</div>
      <label class="lbl">Region:</label>
      <div class="inp">{{ form.reg }}</div>
      <label class="lbl">Certificate:</label>
      <div class="inp">{{ form.cert }}</div>
      <label class="lbl">Recouped Ad. Payment:</label>
      <div class="inp">{{ form.reco }}</div>
      <label class="lbl">Project Status:</label>
      <div class="inp">{{ form.progress }}</div>
    </fieldset>
  </form>


</body>


<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>
<script>
$("#example_id").ionRangeSlider();
</script>
<script>
$(document).ready(function () {
  $("mySlider").ionRangeSlider({
    min: 0,
    max: 100,
    from: 0,
    step: 1,
    prefix: ""
  });
});

</script>
<!-- <script src="js/summernote/summernote-bs4.min.js"></script>
<script>
  $(function () {
    // Summernote
    $('#summernote').summernote()

    // CodeMirror
    CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
      mode: "htmlmixed",
      theme: "monokai"
    });
  })
</script> -->
</html>

{% endblock content %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>CAAP Project Monitoring</title>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}




</head>

<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
<link rel="stylesheet" href="{% static '../../dist/css/adminlte.min.css'}">


<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js'%}"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="./index.css" />

<link rel="stylesheet"
  href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,600;0,700;0,800;1,500;1,700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Jaldi:wght@400;700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Hammersmith One:wght@400&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fugaz One:wght@400&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cousine:wght@700&display=swap" />
<style>
  @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap');
  .container-fluid {
    width: 90% !important;
  }

  body{
    font-family: 'Lato';
}
.form-field{
    width: 30%;
    display: block;
    margin-left: auto;
    margin-right: auto;
    margin-top: 10vh;
}


.lbl{
    width: 100%;
    margin-top: 3vh;
}
.input{
    width: 100%;
}
.submit{
  margin-top: 3vh;
  padding: 10px;
  background-color: #3A98B9;
  color: #ffff;
  border: none;
  border-radius: 10px;
  width: 100%;
  text-align: center;
}
  nav {
    background-color: white;
  }

  .nav-hdr{
    display: flex;
    gap: 1vh;
    align-items: center;
    margin-left: 3vh;
  }
  .caaplogo{
    width: 100px;
    height: auto;
  }
  .nav-title{
    font-weight: bold; 
    font-family: 'Helvetica'; 
    font-size: 2rem;
  }
  #caap{
    background: url('../img/caap.png') no-repeat 150% 30%;
    background-size: 250px;
  }
  a {
    font-size: 1.2rem;
  }

  #link {
    background-color: #5cb85c;
    border-radius: 10px;
  }

  ul {
    float: right;
    display: flex;
    align-items: center;
    text-decoration: none;
    list-style: none;
    gap: 5px
  }

  ul li:hover {
    border-radius: 5px;
    transition: .3s ease;

  }
  .header{
    display: flex;
    gap: 2vh;
  }
  .img{
    width: 50px;
    height: auto;
  }
  

  .navbar {

    position: sticky;
    z-index: 2;
    top: 0;
    width: 100%;
  }

  .collapse {
    padding: 10px;
    margin-top: 10px;
    height: 1500px;
    /* Used in this example to enable scrolling */
  }
  .ysa{
    margin-left: 5vh;
    background-color: #d9534f;
    padding: 20px;
    border-radius: 15px;
    color: #ffff;
  }
</style>

</head>
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg">
  <div class="nav-hdr">
    <img class="caaplogo" src="{% static 'img/caap.png' %}" alt="">
    <div class="nav-title" href="#">CAAP Airport Project Profile</div>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="">
      <li class="nav-item active">
        <a class="nav-link" href="/">Dashboard <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/caap_ap">Airport Projects</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="link" href="/addnew">Create Record</a>
      </li>
      <li>
        <a class="ysa" href="/logout">Log Out</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

{% else %}
<nav class="navbar navbar-expand-lg">
  <div class="nav-hdr">
    <img class="caaplogo" src="{% static 'img/caap.png' %}" alt="">
    <div class="nav-title" href="#">CAAP Airport Project Profile</div>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

{% endif %}


<div></div>

<body class="hold-transition sidebar-mini" style="background-color:#F9F9F9;">
  <div>

    <div class="container-fluid">

      {% if user.is_authenticated %}
        {% block content %}{% endblock %}
      {% else %}

      <div class="field-container">

        <div class="form-field">
          <div class="header">
            <h2>Login first sheesh </h2>
            <img class="img" src="{% static 'img/sheesh.jpg' %}" alt="avatar">
          </div>
          <form class="field-set" method="post">
            {% csrf_token %}
            <label class="lbl" for="username">Username:</label>
            <input class="input" type="text" name="username" required>
            <label class="lbl" for="password">Password:</label>
            <input class="input" type="password" name="password" required>
            <button class="submit" type="submit">Login</button>
          </form>
        </div>
      </div>

      {% endif %}
      <div class="row">
        
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>

</html>

myapp/templates/edit.html
{% extends "base.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}

<head>
   <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
   <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
</head>

<div class="col-md-12">
   <h4></h4>
   <form method="POST" class="post-form" action="/update/{{employee.id}}">
      {% csrf_token %}
      <div class="container">
         <br>
         <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
               <h3>Update Details</h3>
            </div>
         </div>

         <!-- <div id="summernote"></div> -->

         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Location:</label>
            <div class="col-sm-4">
               <textarea id="summernote">{{ employee.loc }}</textarea>
            </div>
         </div>
         
         

         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Description:</label>
            <div class="col-sm-4">
               <textarea type="text" class="form-control" name="desc" id="id_desc" required maxlength="1000"
                  value="{{ employee.desc }}" />{{ employee.desc }}</textarea>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Funding Particulars:</label>
            <div class="col-sm-4">
               <textarea type="text" class="form-control" name="fund" id="id_fund" required maxlength="1000"
                  value="{{ employee.fund }}" />{{ employee.fund }}</textarea>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Contract Description:</label>
            <div class="col-sm-4">
               <textarea type="text" class="form-control" name="cont" id="id_cont" required maxlength="1000"
                  value="{{ employee.cont }}" />{{ employee.cont }}</textarea>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Project Profile:</label>
            <div class="col-sm-4">
               <textarea type="text" class="form-control" name="proj_profile" id="id_proj_profile" required
                  maxlength="1000" value="{{ employee.proj_profile }}" />{{ employee.proj_profile }}</textarea>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Project Status:</label>
            <div class="col-sm-4">
               <textarea type="text" class="form-control" name="proj_stat" id="id_proj_stat" required maxlength="1000"
                  value="{{ employee.proj_stat }}" />{{ employee.proj_stat }}</textarea>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Slippage:</label>
            <div class="col-sm-4">
               <input type="text" class="form-control" name="slip" id="id_slip" required maxlength="1000"
                  value="{{ employee.slip }}" /></input>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Contract Amount/ Budget:</label>
            <div class="col-sm-4">
               <input type="text" class="form-control" name="budg" id="id_budg"
                  value="{{ employee.budg }}" /></input>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Agency:</label>
            <div class="col-sm-4">
               <input type="text" class="form-control" name="agency" id="id_agency" required maxlength="1000"
                  value="{{ employee.agency }}" /></input>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Area:</label>
            <div class="col-sm-4">
               <input type="text" class="form-control" name="area" id="id_area" required maxlength="1000"
                  value="{{ employee.area }}" /></input>
            </div>
         </div>

         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Region:</label>
            <div class="col-sm-4">
               <input type="text" class="form-control" name="reg" id="id_reg" required maxlength="1000"
                  value="{{ employee.reg }}" /></input>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Certificate:</label>
            <div class="col-sm-4">
               <input type="text" class="form-control" name="cert" id="id_cert" required maxlength="1000"
                  value="{{ employee.cert }}" /></input>
            </div>
         </div>
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Recouped Ad. Payment:</label>
            <div class="col-sm-4">
               <input type="text" class="form-control" name="reco" id="id_reco" required maxlength="1000"
                  value="{{ employee.reco }}" /></input>
            </div>
         </div>
         
         <div id="mySlider">{{ form.progress }}</div>
         <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
               <button type="submit" class="btn btn-success btn-lg">Update</button>
            </div>
         </div>
      </div>
   </form>

   <script>
      $('#summernote').summernote({
        placeholder: 'Hello stand alone ui',
        tabsize: 2,
        height: 120,
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['table', ['table']],
          ['insert', ['link', 'picture', 'video']],
          ['view', ['fullscreen', 'codeview', 'help']]
        ]
      });
    </script>
   {% endblock content %}

myapp/templates/login.html
{% if user.is_authenticated %}
  <p>Welcome, {{ user.username }}!</p>
  <a href="logout">Logout</a>
{% else %}
  <form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" required>
    <label for="password">Password:</label>
    <input type="password" name="password" required>
    <button type="submit">Login</button>
  </form>
{% endif %}

myapp/templates/signup.html
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" required>
    <label for="password">Password:</label>
    <input type="password" name="password" required>
    <button type="submit">Register</button>
  </form>